development: &default
  adapter: postgresql
  database: parse_api_development
  username: parse_api
  password: secret
  host: localhost 
  encoding: utf8
  min_messages: warning
  pool: 2
  timeout: 5000

test: 
  <<: *default
  database: parse_api_test