# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4347a994091af4d012744cad179052152448cde7f28871f1dcb2b380303df7614c1a0df2e5b3f4e0aadae50fbd57d7d75431965c5b30e4246aefb893e8fd4c2c

test:
  secret_key_base: 5df0681356db8e9a11a641f77cd3a58c464ea1888b39d18c66111bcd604b047ceb5ad86bc36a517b381e862fa27c29871775c98e2e000cf777e1816138e84b42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
